package com.axonbase.jdbc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SqlTranslatorTest {

    @Test void createTable() {
        String sql = "CREATE TABLE person (id bigint generated by default as identity, name varchar(255), age integer, primary key (id))";
        String expected = "DEFINE TABLE person SCHEMAFULL; DEFINE FIELD name ON TABLE person TYPE string; DEFINE FIELD age ON TABLE person TYPE int;";
        assertEquals(expected, SqlTranslator.translate(sql));
    }

    @Test void createTableWithoutConstraints() {
        String sql = "CREATE TABLE employee (name text, salary decimal)";
        String expected = "DEFINE TABLE employee SCHEMAFULL; DEFINE FIELD name ON TABLE employee TYPE string; DEFINE FIELD salary ON TABLE employee TYPE decimal;";
        assertEquals(expected, SqlTranslator.translate(sql));
    }

    @Test void insertInto() {
        String sql = "INSERT INTO person (name, age) VALUES ('Alice', 30)";
        String expected = "CREATE person CONTENT {name: 'Alice', age: 30}";
        assertEquals(expected, SqlTranslator.translate(sql));
    }

    @Test void selectSimple() {
        assertEquals("SELECT * FROM person", SqlTranslator.translate("SELECT * FROM person"));
    }

    @Test void selectCount() {
        assertEquals("SELECT count() AS total FROM person", SqlTranslator.translate("SELECT count(*) AS total FROM person"));
    }

    @Test void selectWithAlias() {
        assertEquals("SELECT name, age FROM person", SqlTranslator.translate("SELECT p.name, p.age FROM person p"));
    }

    @Test void updateSimple() {
        assertEquals("UPDATE person SET age = 31 WHERE name = 'Alice'",
            SqlTranslator.translate("UPDATE person SET age = 31 WHERE name = 'Alice'"));
    }

    @Test void deleteFrom() {
        assertEquals("DELETE person WHERE id = 1",
            SqlTranslator.translate("DELETE FROM person WHERE id = 1"));
    }

    @Test void dropTable() {
        assertEquals("REMOVE TABLE person", SqlTranslator.translate("DROP TABLE person IF EXISTS"));
    }

    @Test void dropTableSimple() {
        assertEquals("REMOVE TABLE person", SqlTranslator.translate("DROP TABLE person"));
    }

    @Test void selectWithWhereOrderLimit() {
        assertEquals("SELECT name FROM person WHERE age > 25 ORDER BY name ASC LIMIT 10",
            SqlTranslator.translate("SELECT name FROM person WHERE age > 25 ORDER BY name ASC LIMIT 10"));
    }

    @Test void nativeAxonQLPassthrough() {
        assertEquals("CREATE person CONTENT {name: 'Test'}", SqlTranslator.translate("CREATE person CONTENT {name: 'Test'}"));
        assertEquals("SELECT VALUE ->knows->person FROM person:1", SqlTranslator.translate("SELECT VALUE ->knows->person FROM person:1"));
        assertEquals("RELATE person:1 ->knows-> person:2", SqlTranslator.translate("RELATE person:1 ->knows-> person:2"));
        assertEquals("BEGIN TRANSACTION", SqlTranslator.translate("BEGIN TRANSACTION"));
    }

    @Test void truncate() {
        assertEquals("DELETE person", SqlTranslator.translate("TRUNCATE TABLE person"));
    }

    @Test void alterAddColumn() {
        assertEquals("DEFINE FIELD email ON TABLE person TYPE string", SqlTranslator.translate("ALTER TABLE person ADD COLUMN email VARCHAR(255)"));
    }
}