package com.axonbase.jdbc;

import com.axonbase.common.Messages;
import com.axonbase.sdk.Axon;
import com.axonbase.value.AxonValue;

import java.sql.*;
import java.util.*;

/**
 * Statement JDBC do AxonBase. Traduz SQL para AxonQL e executa via SDK.
 */
public class AxonStatement implements Statement {

    protected final Axon axon;
    protected final String ns;
    protected final String db;
    protected final boolean translate;
    protected AxonValue currentResult;
    protected boolean closed;
    protected boolean hasResultSet;
    protected int maxRows;
    protected int queryTimeout;

    public AxonStatement(Axon axon, String ns, String db) {
        this(axon, ns, db, false);
    }

    public AxonStatement(Axon axon, String ns, String db, boolean translate) {
        this.axon = axon;
        this.ns = ns;
        this.db = db;
        this.translate = translate;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        execute(sql);
        return getResultSet();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        execute(sql);
        return currentResult != null && currentResult.isArray() ? currentResult.asArray().size() : 0;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        try {
            if (sql == null) return false;
            String translated = translate ? SqlTranslator.translate(sql) : sql;
            String upper = translated.toUpperCase().trim();
            if ((upper.startsWith("SELECT ") || upper.startsWith("SELECT'"))
                && !upper.startsWith("SELECT VALUE")
                && !upper.contains(" FROM ") && !upper.contains("\nFROM ")) {
                currentResult = AxonValue.array(List.of(AxonValue.object(Map.of("ok", AxonValue.str("1")))));
                hasResultSet = true;
                return true;
            }
            if (axon == null || !axon.isConnected()) {
                throw new SQLException(Messages.get("jdbc_connection_closed"));
            }
            currentResult = axon.query(translated);
            hasResultSet = currentResult != null && currentResult.isArray();
            return hasResultSet;
        } catch (SQLException e) {
            throw e;
        } catch (Exception e) {
            throw new SQLException(Messages.get("jdbc_execute_failed", sql), e);
        }
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        if (currentResult == null) return null;
        return JdbcProxy.create(ResultSet.class, new AxonResultSetBackend(currentResult));
    }

    @Override
    public int getUpdateCount() throws SQLException {
        if (hasResultSet) return -1;
        return currentResult != null && currentResult.isArray() ? currentResult.asArray().size() : -1;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        hasResultSet = false;
        currentResult = null;
        return false;
    }

    @Override
    public int getMaxRows() throws SQLException { return maxRows; }
    @Override
    public void setMaxRows(int max) throws SQLException { this.maxRows = max; }

    @Override
    public int getQueryTimeout() throws SQLException { return queryTimeout; }
    @Override
    public void setQueryTimeout(int seconds) throws SQLException { this.queryTimeout = seconds; }

    @Override
    public void close() throws SQLException { closed = true; currentResult = null; }
    @Override
    public boolean isClosed() throws SQLException { return closed; }

    @Override
    public Connection getConnection() throws SQLException { return null; }

    @Override public void setFetchDirection(int direction) throws SQLException {}
    @Override public int getFetchDirection() throws SQLException { return ResultSet.FETCH_FORWARD; }
    @Override public void setFetchSize(int rows) throws SQLException {}
    @Override public int getFetchSize() throws SQLException { return 0; }
    @Override public int getResultSetConcurrency() throws SQLException { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int getResultSetType() throws SQLException { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int getResultSetHoldability() throws SQLException { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }

    @Override public void setCursorName(String name) throws SQLException {}
    @Override public boolean getMoreResults(int current) throws SQLException { return false; }
    @Override public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { return null; }
    @Override public void setPoolable(boolean poolable) throws SQLException {}
    @Override public boolean isPoolable() throws SQLException { return false; }
    @Override public void closeOnCompletion() throws SQLException {}
    @Override public boolean isCloseOnCompletion() throws SQLException { return false; }
    @Override public void cancel() throws SQLException {}
    @Override public void setEscapeProcessing(boolean enable) throws SQLException {}
    @Override public void setMaxFieldSize(int max) throws SQLException {}
    @Override public int getMaxFieldSize() throws SQLException { return 0; }
    @Override public int[] executeBatch() throws SQLException { return new int[0]; }
    @Override public void clearBatch() throws SQLException {}
    @Override public void addBatch(String sql) throws SQLException {}
    @Override public SQLWarning getWarnings() throws SQLException { return null; }
    @Override public void clearWarnings() throws SQLException {}
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return iface.cast(this); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return iface.isInstance(this); }
}
